export const PRODUCT_CATEGORIES = [
  "SIGARETTE",
  "SIGARI",
  "SIGARETTI",
  "FIUTO E MASTICO",
  "TRINCIATI PER SIGARETTA",
  "ALTRI TABACCHI DA FUMO",
  "PRODOTTI DA INALAZIONE SENZA COMBUSTIONE",
  "PRODOTTI DA INALAZIONE SENZA COMBUSTIONE ELETTRONICA",
  "ACCESSORI",
];

export function shortCategory(label = "") {
  const map = {
    "PRODOTTI DA INALAZIONE SENZA COMBUSTIONE ELETTRONICA": "ELETTRONICA",
    "PRODOTTI DA INALAZIONE SENZA COMBUSTIONE": "INALAZIONE",
    "TRINCIATI PER SIGARETTA": "TRINCIATI",
    "ALTRI TABACCHI DA FUMO": "ALTRI TABACCHI",
    "FIUTO E MASTICO": "FIUTO/MASTICO",
  };
  return map[label] || label;
}

export function defaultLotForCategory(category) {
  if (category === "SIGARETTE") return 10;
  if (
    category === "PRODOTTI DA INALAZIONE SENZA COMBUSTIONE" ||
    category === "PRODOTTI DA INALAZIONE SENZA COMBUSTIONE ELETTRONICA"
  ) return 5;
  return 1;
}
